#!/usr/bin/env python3
"""Check whether a second run reproduces the published medians.

    python3 scripts/compare_runs.py PUBLISHED_HOST_DIR REPLICA_HOST_DIR [--md PATH] [--json PATH]

Both arguments are host directories (results/<host>/ layout: one directory
per model id with sweep/ and context/ inside). For every metric present in
both runs (each sweep configuration's prompt and generation tests, and each
context-length point's prompt and generation throughput) the script compares
the two medians.

Acceptance rule, as stated in the README: a metric reproduces when the
replica's median differs from the published median by no more than the
published run's inter-quartile range. The script also reports the relative
difference, because with three repetitions an IQR can be very narrow.
Output is deterministic.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import summarize  # noqa: E402


def metrics(host_dir):
    """{(model, stage, item, test): stat} for every published-eligible number."""
    out = {}
    for mid, entry in summarize.load_host(host_dir).items():
        sw = entry.get("sweep")
        if sw:
            for name, c in sw["configs"].items():
                for test, stat in c["tests"].items():
                    if stat:
                        out[(mid, "sweep", name, test)] = stat
        cx = entry.get("context")
        if cx:
            for p, pt in cx["points"].items():
                for kind in ("pp", "tg"):
                    if pt.get(kind):
                        out[(mid, "context", "p%d" % p, kind)] = pt[kind]
    return out


def compare(a_dir, b_dir):
    a, b = metrics(a_dir), metrics(b_dir)
    rows = []
    for key in sorted(set(a) & set(b)):
        sa, sb = a[key], b[key]
        delta = sb["median"] - sa["median"]
        rel = (delta / sa["median"] * 100.0) if sa["median"] else None
        rows.append({"model": key[0], "stage": key[1], "item": key[2], "test": key[3],
                     "published_median": sa["median"], "published_iqr": sa["iqr"],
                     "replica_median": sb["median"], "replica_iqr": sb["iqr"],
                     "delta": delta, "delta_pct": rel,
                     "within_published_iqr": abs(delta) <= sa["iqr"]})
    only_a = sorted("/".join(k) for k in set(a) - set(b))
    only_b = sorted("/".join(k) for k in set(b) - set(a))
    by_model = {}
    for r in rows:
        m = by_model.setdefault(r["model"], {"metrics": 0, "within_published_iqr": 0, "abs_delta_pct": []})
        m["metrics"] += 1
        m["within_published_iqr"] += int(r["within_published_iqr"])
        if r["delta_pct"] is not None:
            m["abs_delta_pct"].append(abs(r["delta_pct"]))
    for m in by_model.values():
        vals = m.pop("abs_delta_pct")
        m["median_abs_delta_pct"] = summarize.med_iqr(vals)["median"] if vals else None
        m["max_abs_delta_pct"] = max(vals) if vals else None
    return {"schema": "edge-inference-bench/compare/v1",
            "published": os.path.basename(os.path.normpath(a_dir)),
            "replica": os.path.relpath(os.path.normpath(b_dir), os.path.dirname(os.path.normpath(a_dir))),
            "rule": "reproduces when |replica median - published median| <= published IQR",
            "by_model": by_model, "rows": rows, "only_in_published": only_a, "only_in_replica": only_b}


def render(cmp):
    L = ["# Reproducibility: `%s` against `%s`" % (cmp["replica"], cmp["published"]), "",
         "Rule: a metric reproduces when |replica median - published median| <= the published run's "
         "inter-quartile range. Generated by `scripts/compare_runs.py`; do not edit by hand.", "",
         "| Model | Metrics compared | Within published IQR | Median abs. difference | Largest abs. difference |",
         "|---|---|---|---|---|"]
    for mid, m in sorted(cmp["by_model"].items()):
        L.append("| `%s` | %d | %d (%.0f%%) | %s | %s |" % (
            mid, m["metrics"], m["within_published_iqr"], 100.0 * m["within_published_iqr"] / m["metrics"],
            "%.1f%%" % m["median_abs_delta_pct"] if m["median_abs_delta_pct"] is not None else "n/a",
            "%.1f%%" % m["max_abs_delta_pct"] if m["max_abs_delta_pct"] is not None else "n/a"))
    L += ["", "## Every metric", "",
          "| Model | Stage | Item | Test | Published median (IQR) | Replica median (IQR) | Difference | Within IQR |",
          "|---|---|---|---|---|---|---|---|"]
    for r in cmp["rows"]:
        L.append("| `%s` | %s | %s | %s | %.2f (%.2f) | %.2f (%.2f) | %+.1f%% | %s |" % (
            r["model"], r["stage"], r["item"], r["test"], r["published_median"], r["published_iqr"],
            r["replica_median"], r["replica_iqr"], r["delta_pct"] if r["delta_pct"] is not None else 0.0,
            "yes" if r["within_published_iqr"] else "no"))
    if cmp["only_in_published"] or cmp["only_in_replica"]:
        L += ["", "Present in only one run: published %s; replica %s." % (
            ", ".join(cmp["only_in_published"]) or "none", ", ".join(cmp["only_in_replica"]) or "none")]
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("published")
    ap.add_argument("replica")
    ap.add_argument("--md")
    ap.add_argument("--json")
    args = ap.parse_args(argv)
    cmp = compare(args.published, args.replica)
    md = render(cmp)
    if args.md:
        with open(args.md, "w", encoding="utf-8") as fh:
            fh.write(md)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            fh.write(json.dumps(cmp, indent=2, sort_keys=True) + "\n")
    if not args.md and not args.json:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
